[[services]]
name = "backend"
directory = "backend"

[services.build]
builder = "nixpacks"
buildCommand = "npm install"

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "frontend"
directory = "frontend"

[services.build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npx serve -s build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.deploy.envs]
REACT_APP_API_URL = "https://${RAILWAY_STATIC_URL}"
