[[services]]
name = "backend"
directory = "backend"

[services.build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "frontend"
directory = "frontend"

[services.build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.deploy.envs]
REACT_APP_API_URL = "https://${RAILWAY_STATIC_URL}"
