[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm install && npm start & cd frontend && npm install && npm run build && npx serve -s build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
REACT_APP_API_URL = "https://${RAILWAY_STATIC_URL}"
