[[services]]
name = "yt-answer-finder"
directory = "."

[services.build]
builder = "DOCKERFILE"
dockerfile = "backend/Dockerfile"

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
