[[services]]
name = "yt-answer-finder"
directory = "backend"

[services.build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
